name: Pytest

on:
	push:
		branches: ["master"]
	pull_request:
		branches: ["master"]
	workflow_dispatch:

jobs:
	run_tests:name: Pytest

on:
	push:
		branches: ["master"]
	pull_request:
		branches: ["master"]
	workflow_dispatch:

jobs:
	run_tests:
		runs_on: debian-latest
		steps:
			uses: actions/checkout@v3
			
			name: Setup python
			uses: actions/setup-python@v4
			with:
				python-version: "3.10"
				cache: "pip"
			
			name: Install dependencies
			run:
				python -m install --upgrade pip
				pip install -r backend/requirements.pip
			
			name: Unit tests
			run:
				cd backend
				python -m pytest -m unit
		runs_on: debian-latest
		steps:
			uses: actions/checkout@v3
			
			name: Setup python
			uses: actions/setup-python@v4
			with:
				python-version: "3.10"
				cache: "pip"
			
			name: Install dependencies
			run:
				python -m install --upgrade pip
				pip install -r backend/requirements.pip
			
			name: Unit tests
			run:
				cd backend
				python -m pytest -m unit
